version: "2.4"
services:
  frontend:
    image: presentsong/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m
  nginx:
    restart: always
    image: presentsong/docker-nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend
  backend:
    image: presentsong/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: docker-fullstack-mysql.c3iyxkekqgqw.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: MysqlTesting
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    mem_limit: 128m
